### ISSUE TITLE
Blank line breaks cli import

### ISSUE THREAD

**Issue by RexBytes** [RexBytes/pgmonkey#3]
A blank line in an import file breaks the import.
Removal of the blank line allows import to continue successfully.
Need to implement fix to remove/ignore blank lines.

Here is the error.

pgmonkey pgimport --table test.commatest --connconfig testfile.yaml  commatest.csv 

CSV Headers (Original):
['ID', 'Name', 'Age', 'City', 'Occupation', 'Salary']

Formatted Headers for DB:
['id', 'name', 'age', 'city', 'occupation', 'salary']

Starting import for file: commatest.csv into table: test.commatest

Table test.commatest created successfully.
Importing data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 1833.76rows/s]
Traceback (most recent call last):
  File "/home/ubuntu/myvenvs/pgmonkey/bin/pgmonkey", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/myrepos/rex/pgmonkey/src/cli/cli.py", line 50, in main
    cli.run()
  File "/home/ubuntu/myrepos/rex/pgmonkey/src/cli/cli.py", line 43, in run
    args.func(args)
  File "/home/ubuntu/myrepos/rex/pgmonkey/src/cli/cli_import_subparser.py", line 42, in pgimport_handler
    pgimport_manager.import_file(import_file, table_name, connection_config)
  File "/home/ubuntu/myrepos/rex/pgmonkey/src/pgmonkey/managers/pgimport_manager.py", line 22, in import_file
    asyncio.run(importer.run())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/myrepos/rex/pgmonkey/src/pgmonkey/tools/csv_data_importer.py", line 272, in run
    self._sync_ingest(connection)  # Blocking sync ingest
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myrepos/rex/pgmonkey/src/pgmonkey/tools/csv_data_importer.py", line 225, in _sync_ingest
    with cur.copy(
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/ubuntu/myvenvs/pgmonkey/lib/python3.12/site-packages/psycopg/cursor.py", line 275, in copy
    raise ex.with_traceback(None)
psycopg.errors.BadCopyFileFormat: missing data for column "name"
CONTEXT:  COPY commatest, line 11: ""

**Comment by RexBytes** [comment]
Any blank lines in data are skipped. Import works.

Wondering about edge case where there are blank lines at the top of a file... should this return an error or assume the file starts at the first non blank line.  leaving this decision alone at the moment.
